### ISSUE TITLE
Bug in injunctive game

### ISSUE THREAD

**Issue by sbrunswi** [opendigital/smart-energy-game#10]
@charrismatic 
There is a bug in the injunctive game! On the first screen, I already see a mean. This is impossible. 
Please fix this - We can only have a mean in the second round. 

I am sending along the screenshot [here](https://www.dropbox.com/s/ec50459ao8jjrpp/Screen%20Shot%202020-09-30%20at%202.12.49%20PM.png?dl=0)

This text is put on the first round: 

> Last month, you conserved 5 energy tokens, while others conserved 5.5 energy tokens on average. Your energy conservation will eliminate air pollution in the US, which contribute to known health impacts such as childhood asthma and cancer.

This should not be there! Clarify what is going on here.

**Comment by charrismatic** [comment]
This is now fixed becf4a871a3b4c80ef6a0470d6a80dccbb3cb822
