### ISSUE TITLE
Bug in descriptive norm game

### ISSUE THREAD

**Issue by sbrunswi** [opendigital/smart-energy-game#11]
After identifying the bug in the injunctive norm game I noticed that also the descriptive norm game has a bug. 

On the first page of the game (month 1), there you display an average: 

[link](https://www.dropbox.com/s/uphqcgvj43uw5dq/Screen%20Shot%202020-09-30%20at%202.23.09%20PM.png?dl=0)

> Last month, you conserved 5 energy tokens, while others conserved 5.5 energy tokens on average.

I assume this is a database storage issue! I did not see this yesterday but it is completely messing up the experimental design. So this needs to be corrected in both the descriptive and injunctive norm game!

**Comment by charrismatic** [comment]
The game is implemented according to the requested design document.

See attached image.

![Screenshot_20200930-142756.png](https://user-images.githubusercontent.com/7072452/94725191-63552900-0329-11eb-8c9d-ca11edb1f237.png)

**Comment by sbrunswi** [comment]
You cannot calculate a mean based on nothing! So basically we add a fake phase 0 before!

**Comment by sbrunswi** [comment]
Here are the corrected slides 
[link](https://www.dropbox.com/s/qj46e12uaeb6col/Treatments%20v3.pptx?dl=0)
![Screen Shot 2020-09-30 at 3 00 51 PM](https://user-images.githubusercontent.com/12464227/94728309-0a3bc400-032e-11eb-913f-d78643884142.png)
![Screen Shot 2020-09-30 at 3 00 58 PM](https://user-images.githubusercontent.com/12464227/94728328-0f007800-032e-11eb-892f-5ed34cb023e2.png)
![Screen Shot 2020-09-30 at 3 01 05 PM](https://user-images.githubusercontent.com/12464227/94728332-1031a500-032e-11eb-8492-4f9243446a6d.png)
![Screen Shot 2020-09-30 at 3 01 12 PM](https://user-images.githubusercontent.com/12464227/94728337-11fb6880-032e-11eb-9379-c850bdd3c1ba.png)

These are the corrections for month 1!

**Comment by charrismatic** [comment]
This is now fixed becf4a871a3b4c80ef6a0470d6a80dccbb3cb822
