### ISSUE TITLE
Screenshots and Screen recording of visualizations for publications

### ISSUE THREAD

**Issue by sbrunswi** [opendigital/smart-energy-game#12]
For an upcoming publications we need

1) screenshots of all game pages
2) Screen recordings of the game (in particular for the visual game)

@charrismatic can you please make sure we have the correct recordings/screenshots (with the actual month displayed during the experiment)

**Comment by sbrunswi** [comment]
Here is a first recording I did just now with https://drive.google.com/file/d/1Ucl7PGgPytR56tgNl0QcFUKMnnE44HYR/view?usp=drivesdk

**Comment by charrismatic** [comment]
Screenshots are now available for each app section and game type on the shared drive folder 
https://drive.google.com/drive/folders/1WdWcuSLOyJ-s8A2BASIceLbFXRoMnWkW?usp=sharing

**Comment by RCODI** [comment]
Great! So almost done then!
