### ISSUE TITLE
Wrong axis in radial chart - points instead of dollars

### ISSUE THREAD

**Issue by sbrunswi** [opendigital/smart-energy-game#13]
**The problem**: 
The current axis show $ but it needs to be tokens as the unit is tokens in the game. 

**Solution** (as discussed via MS teams last week) 
--> Adjust axis from 0 to 10 tokens  (instead of 0 to 8 $)

**Open issue for discussion**: 
--> Revisit if the grey area should be the mean or should be the 60% goal ( currently it shows the fixed mean but not the actual mean of the group)
--> Option: Find a way to show the actual mean of the group (moving grey area) or draw the line at the 6 tokens (60%) and also label the line with 6 tokens)

**Comment by charrismatic** [comment]
We can change dollars to tokens here easily.

For the changing the scale, the values are set with this line 

```js
circle_edges = [0, 2, 4, 6, 8, 10];
```
if you wanted to highlight a value we need to determine if you are showing the "current round mean", the "overall game mean" or the "target mean value" of 6 the users are aiming for.

We could draw a circular line for that value

**Comment by RCODI** [comment]
Yes - use tokens instead of $ please! 
Let's leave the dotted line for the 6 out for now!

**Comment by charrismatic** [comment]
Axis labels are updated now for the visual game

![Screenshot from 2020-10-01 21-12-43](https://user-images.githubusercontent.com/7072452/94878282-e7430a00-042a-11eb-8b94-3fdc86cebda0.png)

**Comment by sbrunswi** [comment]
Can u Make the 10 visible as well.

**Comment by charrismatic** [comment]
Attaching two options here after discussion about axis labels not being readable.

The first only adds the 10 label (no color change), the second updates the label font and adds color contrast for better visibility

![Screenshot from 2020-10-02 00-29-16](https://user-images.githubusercontent.com/7072452/94888215-5ed26280-0446-11eb-8d3e-b5a1d28fdfd5.png)
![Screenshot from 2020-10-02 00-28-51](https://user-images.githubusercontent.com/7072452/94888216-5f6af900-0446-11eb-9046-76a01ef3f7aa.png)

**Comment by sbrunswi** [comment]
Can you do open 1? Perfect

**Comment by charrismatic** [comment]
Updated: adab600f289f19dee7a3c59d561ceb10a7d801fa
