### ISSUE TITLE
Treatments

### ISSUE THREAD

**Issue by promann** [opendigital/smart-energy-game#8]
We need to add **treatments** to the base game:

0. Base Game (what we already have)
1. **Descriptive Norm** (text based treatment) on decision pages
2. **Injunctive Health Message** (text based treatment) on decision pages
3. **Proximity chart** (visual feedback) on decision feedback pages in place of the table in the control.
4. **Enclosure chart** (visual feedback) on decision feedback pages in place of the table in the control.

Please see the text based treatments illustrated here: https://www.dropbox.com/s/wm3itpxj0aof58y/Treatments%20v3.pptx?dl=0
Shatayu’s animated charts can be found here: https://github.com/RCODI/oTreeGame/branches (Since I cannot visually look at the charts I am not sure if they are the correct ones.)

**Eliminate options if they have:** 
- no animations (because we want animation effects in the charts where they move from their previous rounds location to their new round loaction)
- full (because we do not want charts to show up during the 2 round test game).

**Comment by charrismatic** [comment]
completed 56fe2139beb4ce26c2cea97918dddee1f485ca2c
