### ISSUE TITLE
Implementation of Treatment and "clear cut experiments"

### ISSUE THREAD

**Issue by sbrunswi** [opendigital/smart-energy-game#9]
Experimental treatments: 
1. Base Game
2. Descriptive Norm
3. Injunctive Norm (environmental message)
4. Proximity Chart (optional)
5. Enclosure Chart

Ideal situation: All games  1 to 3 are launched at the same time/same day  - e.g. this Friday! 

Timing if we cannot launch in parallel: 
Monday - September 28th - 1 
Tuesday - September 29th - 2 
Wednesday - September 30th - 3 

September 30th to October 4th: Data analysis using game data as well as survey data (analysis plan to be developed by Sabine) 

Same time of the day - afternoon EST

Visualization games
Thursday, October 1st - 5
Monday, October 5th  - 4 (Proximity Chart or alternative visualization chart). 

Data analysis: Thursday October 1st, 

The problem: Participants cannot enroll in two games! It is a in between subject study! 
Potential solution: Block participants to enroll in two games

**Comment by sbrunswi** [comment]
Actual implementation: 
Monday - September 28th - 1 (base game) 3:30 
Tuesday - September 29th - 2 ( descriptive game) 3:30
Wednesday - September 30th - 3 ( injunctive game) 3:30
Thursday - October 1st - 2 corrected (at 3:30)
Friday - October 2nd - 5 (enclosure) 3:30

**Comment by charrismatic** [comment]
All experiments have been run now
